version: "3.8"


services:
  vue-template:
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - NODE_ENV=prod
    build:
      context: ./client
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro