version: "3.8"


services:
  vue-template:
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - NODE_ENV=dev
    build:
      context: ./client
      dockerfile: Dockerfile_dev
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./client:/app